[versions]
digiaui = "1.0.0"
digiaexpr = "1.0.0"
kotlin = "1.9.0"
compose = "1.4.3"
quickjs-wrapper = "3.2.3"
composeBom = "2023.03.00"
coroutines = "1.7.3"

[libraries]
# Digia UI
digiaexpr = { module = "com.digia:digiaexpr", version.ref = "digiaexpr" }

# AndroidX Core
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# JSON
gson = "com.google.code.gson:gson:2.10.1"

# Networking
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"

# DataStore
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"

# ViewModel
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.6.2"

# Navigation
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.6"

# Image Loading
coil-compose = "io.coil-kt:coil-compose:2.5.0"

# QuickJS
quickjs-wrapper-android = { module = "wang.harlon.quickjs:wrapper-android", version.ref = "quickjs-wrapper" }
quickjs-wrapper-java = { module = "wang.harlon.quickjs:wrapper-java", version.ref = "quickjs-wrapper" }

[plugins]
android-application = { id = "com.android.application", version = "8.1.4" }
android-library = { id = "com.android.library", version = "8.1.4" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

