[versions]
digia_expr_kt = "v1.0.0-beta.2"
kotlin = "1.9.0"
compose = "1.4.3"
lottieCompose = "6.7.1"
media3Exoplayer = "1.9.0"
media3UiCompose = "1.9.0"
media3UiComposeMaterial3 = "1.9.0"
quickjs-wrapper = "3.2.3"
composeBom = "2023.03.00"
coroutines = "1.7.3"
runtime = "1.10.0"
composeMaterial3 = "1.5.6"
foundationLayout = "1.10.0"
animationCore = "1.10.0"
ui = "1.10.0"
browser = "1.9.0"
media3Ui = "1.9.0"
uiGraphics = "1.10.0"
foundation = "1.10.1"
#navigationRuntimeKtx = "2.9.6"

[libraries]
# Digia UI
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3UiCompose" }
androidx-media3-ui-compose-material3 = { module = "androidx.media3:media3-ui-compose-material3", version.ref = "media3UiComposeMaterial3" }
digia_expr_kt = { module = "com.github.Digia-Technology-Private-Limited:digia_expr_kt", version.ref = "digia_expr_kt" }

# AndroidX Core
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# JSON
gson = "com.google.code.gson:gson:2.10.1"

# Networking
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"

# DataStore
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"

# ViewModel
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.6.2"

# Navigation
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.8.0"

# Kotlin Serialization
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"

# Image Loading
coil-compose = "io.coil-kt:coil-compose:2.5.0"

# QuickJS
quickjs-wrapper-android = { module = "wang.harlon.quickjs:wrapper-android", version.ref = "quickjs-wrapper" }
quickjs-wrapper-java = { module = "wang.harlon.quickjs:wrapper-java", version.ref = "quickjs-wrapper" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "animationCore" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
#androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version = "8.1.4" }
android-library = { id = "com.android.library", version = "8.1.4" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

